# See https://github.com/crate-ci/typos/blob/master/docs/reference.md for how to configure the typo checker.

[files]
# Add files to this list if you don't want these files to be checked by the typo checker.
# For e.g., `extend-exclude = [ "foo", "*.bar" ]` states that the file named "foo" and all files ends with ".bar" will be ignored by the typo checker.
extend-exclude = []

# Add word correction as key-value pairs. 
# For e.g., `"abc" = "def"` states that the word `abc` is miss spelled and its correct form is `def`.
[default.extend-words]
